version: "3.6"
services:
  open-id-connect-api:
    environment:
      - FLUX_OPEN_ID_CONNECT_API_PROVIDER_URL=...
      - FLUX_OPEN_ID_CONNECT_API_PROVIDER_CLIENT_ID_FILE=/run/secrets/open_id_connect_provider_client_id
      - FLUX_OPEN_ID_CONNECT_API_PROVIDER_CLIENT_SECRET_FILE=/run/secrets/open_id_connect_provider_client_secret
      - FLUX_OPEN_ID_CONNECT_API_PROVIDER_REDIRECT_URI=https://%host%/callback
      - FLUX_OPEN_ID_CONNECT_API_SESSION_CRYPT_SECRET_FILE=/run/secrets/open_id_connect_session_crypt_secret
    image: docker-registry.fluxpublisher.ch/flux-open-id-connect/api:latest
    restart: always
    secrets:
      - open_id_connect_provider_client_id
      - open_id_connect_provider_client_secret
      - open_id_connect_session_crypt_secret
  other-service:
    depends_on:
      - open-id-connect-api
    environment:
      [- FLUX_OPEN_ID_CONNECT_API_HOST=open-id-connect-api]
      [- FLUX_OPEN_ID_CONNECT_API_PORT=9501]
secrets:
  open_id_connect_provider_client_id:
    file: ./data/secrets/open_id_connect_provider_client_id
  open_id_connect_provider_client_secret:
    file: ./data/secrets/open_id_connect_provider_client_secret
  open_id_connect_session_crypt_secret:
    file: ./data/secrets/open_id_connect_session_crypt_secret
